<?php

namespace MacropaySolutions\KernelDev\Support;

class IdeMetaGenerator
{
    /**
     * $basePath The root path of the active project
     * @throws \ReflectionException
     */
    public static function generate(string $basePath): bool
    {
        $appClass = \class_exists(\App\Application::class)
            ? \App\Application::class
            : \MacropaySolutions\Framework\Application::class;

        $reflection = new \ReflectionClass($appClass);
        $abstractAliases = $reflection->getDefaultProperties()['abstractAliases'] ?? [];

        $meta = "<?php\n\n// This file is auto-generated by Macropay-Solutions PHP-Kernel-Dev.\n\n";
        $meta .= "namespace PHPSTORM_META {\n";

        // 1. Build the map once
        $map = "map([\n";

        foreach ($abstractAliases as $alias => $classes) {
            $concrete = null;

            // Iterate through the array to find the first valid, most-specific class
            foreach ((array)$classes as $class) {
                if (\class_exists($class) || \interface_exists($class)) {
                    $concrete = $class;

                    break;
                }
            }

            // Fallback to the last item just in case nothing valid was found
            $concrete = $concrete ?? \end($classes);

            $map .= \sprintf("        '%s' => \\%s::class,\n", $alias, $concrete);
        }

        $map .= "        '' => '@',\n";
        $map .= '    ])';

        // 2. Apply the map to all DI entry points
        $meta .= "    override(\\app(0), {$map});\n";
        $meta .= "    override(\\di(0), {$map});\n";
        $meta .= "    override(\\App\\Application::make(0), {$map});\n";
        $meta .= "    override(\\App\\Application::makeWith(0), {$map});\n";
        $meta .= "    override(\\App\\Application::get(0), {$map});\n";
        $meta .= "    override(\\MacropaySolutions\\Framework\\Application::make(0), {$map});\n";
        $meta .= "    override(\\MacropaySolutions\\Framework\\Application::makeWith(0), {$map});\n";
        $meta .= "    override(\\MacropaySolutions\\Framework\\Application::get(0), {$map});\n";
        $meta .= "    override(\\MacropaySolutions\\Kernel\\Container\\Container::make(0), {$map});\n";
        $meta .= "    override(\\MacropaySolutions\\Kernel\\Container\\Container::makeWith(0), {$map});\n";
        $meta .= "    override(\\MacropaySolutions\\Kernel\\Container\\Container::get(0), {$map});\n";
        $meta .= "    override(\\MacropaySolutions\\Kernel\\Container\\Container::resolve(0), {$map});\n";
        $meta .= "    override(\\MacropaySolutions\\Kernel\\Contracts\\Container\\Container::resolve(0), {$map});\n";
        $meta .= "    override(\\MacropaySolutions\\Kernel\\Contracts\\Container\\Container::make(0), {$map});\n";
        $meta .= "    override(\\MacropaySolutions\\Kernel\\Contracts\\Container\\Container::makeWith(0), {$map});\n";
        $meta .= "    override(\\MacropaySolutions\\Kernel\\Contracts\\Container\\Container::get(0), {$map});\n";
        $meta .= "    override(\\Psr\\Container\\ContainerInterface::get(0), {$map});\n";

        $meta .= "}\n";

        $outputPath = $basePath . '/.phpstorm.meta.php';

        return file_put_contents($outputPath, $meta) !== false;
    }
}
