<?php

namespace MacropaySolutions\KernelDev\Support;

class IdeMetaGenerator
{
    /**
     * $basePath The root path of the active project
     * @throws \ReflectionException
     */
    public static function generate(string $basePath): bool
    {
        $appClass = \class_exists(\App\Application::class)
            ? \App\Application::class
            : \MacropaySolutions\Framework\Application::class;

        $reflection = new \ReflectionClass($appClass);
        $abstractAliases = $reflection->getDefaultProperties()['abstractAliases'] ?? [];

        $mappings = [];

        $exists = static function (string $name): bool {
            try {
                return \class_exists($name) || \interface_exists($name);
            } catch (\Throwable) {
                return false;
            }
        };

        // 1. Process mixed array formats from Application.php (Key=Alias vs Key=FQN)
        foreach ($abstractAliases as $key => $values) {
            $items = array_merge([$key], (array)$values);

            $aliases = [];
            $fqns = [];

            // Separate string aliases from Fully Qualified Names (FQNs)
            foreach ($items as $item) {
                if (\str_contains($item, '\\') || $exists($item)) {
                    $fqns[] = ltrim($item, '\\');

                    continue;
                }

                $aliases[] = $item;
            }

            if ([] === $fqns) {
                continue;
            }

            // Prefer an actual class over an interface if multiple FQNs exist
            $target = $fqns[0];

            foreach ($fqns as $fqn) {
                if ($exists($fqn)) {
                    $target = $fqn;

                    break;
                }
            }

            // Map every string alias to the target FQN
            foreach ($aliases as $alias) {
                $mappings[$alias] = $target;
            }
        }

        // 2. Unconditionally guarantee 'request' overrides regardless of autoloader state
        $requestClass = $exists('App\Request')
            ? 'App\Request'
            : 'MacropaySolutions\Kernel\Http\Request';

        $mappings['request'] = $requestClass;
        $mappings['MacropaySolutions\Kernel\Http\Request'] = $requestClass;

        // 3. Build map string
        $map = "map([\n";

        foreach ($mappings as $aliasKey => $targetClass) {
            $map .= \sprintf("        '%s' => \\%s::class,\n", $aliasKey, $targetClass);
        }

        $map .= "        '' => '@',\n    ])";

        $meta = "<?php\n\n// Auto-generated by Macropay-Solutions PHP-Kernel-Dev.\n\nnamespace PHPSTORM_META {\n";

        // Global Request helper function support
        $meta .= "    override(\\request(0), {$map});\n";

        // DI Entry Points
        $meta .= "    override(\\app(0), {$map});\n";
        $meta .= "    override(\\di(0), {$map});\n";

        // Application Classes
        $meta .= "    override(\\App\\Application::make(0), {$map});\n";
        $meta .= "    override(\\App\\Application::makeWith(0), {$map});\n";
        $meta .= "    override(\\App\\Application::get(0), {$map});\n";
        $meta .= "    override(\\MacropaySolutions\\Framework\\Application::make(0), {$map});\n";
        $meta .= "    override(\\MacropaySolutions\\Framework\\Application::makeWith(0), {$map});\n";
        $meta .= "    override(\\MacropaySolutions\\Framework\\Application::get(0), {$map});\n";

        // Container Implementations
        $meta .= "    override(\\MacropaySolutions\\Kernel\\Container\\Container::make(0), {$map});\n";
        $meta .= "    override(\\MacropaySolutions\\Kernel\\Container\\Container::makeWith(0), {$map});\n";
        $meta .= "    override(\\MacropaySolutions\\Kernel\\Container\\Container::get(0), {$map});\n";
        $meta .= "    override(\\MacropaySolutions\\Kernel\\Container\\Container::resolve(0), {$map});\n";

        // Container Contracts / Interfaces
        $meta .= "    override(\\MacropaySolutions\\Kernel\\Contracts\\Container\\Container::make(0), {$map});\n";
        $meta .= "    override(\\MacropaySolutions\\Kernel\\Contracts\\Container\\Container::makeWith(0), {$map});\n";
        $meta .= "    override(\\MacropaySolutions\\Kernel\\Contracts\\Container\\Container::get(0), {$map});\n";
        $meta .= "    override(\\MacropaySolutions\\Kernel\\Contracts\\Container\\Container::resolve(0), {$map});\n";
        $meta .= "    override(\\Psr\\Container\\ContainerInterface::get(0), {$map});\n";

        $meta .= "}\n";

        return file_put_contents($basePath . '/.phpstorm.meta.php', $meta) !== false;
    }
}