<?php

namespace MacropaySolutions\KernelDev\Support;

class IdeMetaGenerator
{
    /**
     * $basePath The root path of the active project
     * @throws \ReflectionException
     */
    public static function generate(string $basePath): bool
    {
        $appClass = \class_exists(\App\Application::class)
            ? \App\Application::class
            : \MacropaySolutions\Framework\Application::class;

        $reflection = new \ReflectionClass($appClass);
        $abstractAliases = $reflection->getDefaultProperties()['abstractAliases'] ?? [];

        $meta = "<?php\n\n// This file is auto-generated by Macropay-Solutions PHP-Kernel-Dev.\n\n";
        $meta .= "namespace PHPSTORM_META {\n";

        $mappings = [];

        $exists = static function (string $name): bool {
            try {
                return \class_exists($name) || \interface_exists($name);
            } catch (\Throwable) {
                return false;
            }
        };

        foreach ($abstractAliases as $alias => $classes) {
            $classes = (array)$classes;

            // Find the most specific concrete class or interface in the array
            $concrete = null;

            foreach ($classes as $class) {
                if ($exists($class)) {
                    $concrete = $class;

                    break;
                }
            }

            if (!$exists($alias)) {
                // Case A: Key is a string alias (e.g. 'request' => [\MacropaySolutions\Kernel\Http\Request::class])
                $target = $concrete ?? \end($classes);

                if ($target) {
                    $mappings[$alias] = $target;
                }

                continue;
            }

            // Case B: Key is a FQN (e.g. \MacropaySolutions\Kernel\Http\Request::class => ['request'])
            $target = $concrete ?? $alias;

            foreach ($classes as $class) {
                if (!$exists($class)) {
                    $mappings[$class] = $target;
                }
            }

            if ($concrete !== null && $concrete !== $alias) {
                $mappings[$alias] = $concrete;
            }
        }

        // 1. Build the map block
        $map = "map([\n";
        foreach ($mappings as $aliasKey => $targetClass) {
            $map .= \sprintf("        '%s' => \\%s::class,\n", $aliasKey, $targetClass);
        }

        $map .= "        '' => '@',\n";
        $map .= '    ])';

        // 2. Apply the map to all DI entry points
        $meta .= "    override(\\app(0), {$map});\n";
        $meta .= "    override(\\di(0), {$map});\n";

        // Application Classes
        $meta .= "    override(\\App\\Application::make(0), {$map});\n";
        $meta .= "    override(\\App\\Application::makeWith(0), {$map});\n";
        $meta .= "    override(\\App\\Application::get(0), {$map});\n";
        $meta .= "    override(\\MacropaySolutions\\Framework\\Application::make(0), {$map});\n";
        $meta .= "    override(\\MacropaySolutions\\Framework\\Application::makeWith(0), {$map});\n";
        $meta .= "    override(\\MacropaySolutions\\Framework\\Application::get(0), {$map});\n";

        // Container Implementations
        $meta .= "    override(\\MacropaySolutions\\Kernel\\Container\\Container::make(0), {$map});\n";
        $meta .= "    override(\\MacropaySolutions\\Kernel\\Container\\Container::makeWith(0), {$map});\n";
        $meta .= "    override(\\MacropaySolutions\\Kernel\\Container\\Container::get(0), {$map});\n";
        $meta .= "    override(\\MacropaySolutions\\Kernel\\Container\\Container::resolve(0), {$map});\n";

        // Container Contracts / Interfaces
        $meta .= "    override(\\MacropaySolutions\\Kernel\\Contracts\\Container\\Container::make(0), {$map});\n";
        $meta .= "    override(\\MacropaySolutions\\Kernel\\Contracts\\Container\\Container::makeWith(0), {$map});\n";
        $meta .= "    override(\\MacropaySolutions\\Kernel\\Contracts\\Container\\Container::get(0), {$map});\n";
        $meta .= "    override(\\MacropaySolutions\\Kernel\\Contracts\\Container\\Container::resolve(0), {$map});\n";
        $meta .= "    override(\\Psr\\Container\\ContainerInterface::get(0), {$map});\n";

        $meta .= "}\n";

        $outputPath = $basePath . '/.phpstorm.meta.php';

        return file_put_contents($outputPath, $meta) !== false;
    }
}
